version: '3'

services:
  database:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    env_file:
      - .env

volumes:
  database:
